// server/db/dbPreCheck.js  (or wherever your validateSchema lives)
// Overwrite with this content (adjust path/import if your project structure differs)

import readline from 'readline';
import { schemas } from './schema.full.js';
import { dbActions } from './dbActions.js';
import { runDbAction, getPool } from './db.js';
import { buildColumnType } from './column/columnParsing.js';
import { dbTypes, typeMappingsReverse } from './column/dbTypes.js';
import {
  normalizeSpecFromSchema,
  normalizeSpecFromDb,
  compareColumnSpec
} from './normalizeColumnSpec.js';

const env = (process.env.NODE_ENV || '').trim().toLowerCase();
const isProd = env === 'production';

const askConfirmation = async (question) => {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });
  return new Promise((resolve) => {
    rl.question(`${question} (y/n): `, (answer) => {
      rl.close();
      resolve(answer.trim().toLowerCase() === 'y');
    });
  });
};

export const checkDbConnection = async () => {
  try {
    console.log();
    console.log('=> DB Pre-check: Attempting to connect to the database...');
    await getPool().query('SELECT 1 AS ok');
    console.log('>> DB Pre-check: Database connection successful.');
  } catch (err) {
    console.error('>> DB Pre-check: Database connection error:', err, err.message);
    process.exit(1);
  }
}

export async function validateSchema(reTry) {
  console.log()
  console.log(`=> DB Pre-check: ${reTry ? "re-" : ""}Validating schema...`);

  const diffs = [];

  for (const [tableName, schema] of Object.entries(schemas)) {
    const res = await getPool().query(`
      SELECT
    col.column_name,
    col.data_type,
    col.character_maximum_length,
    col.numeric_precision,
    col.numeric_scale,
    col.is_nullable,
    col.column_default,
    col.is_identity,
    col.identity_generation,
    CASE WHEN pk.column_name IS NOT NULL THEN true ELSE false END AS is_primary_key,
    CASE WHEN uq.column_name IS NOT NULL THEN true ELSE false END AS is_unique,
    fk.foreign_table,
    fk.foreign_column,
    fk.on_delete
FROM information_schema.columns col
LEFT JOIN (
    SELECT column_name
    FROM information_schema.key_column_usage kcu
    JOIN information_schema.table_constraints tc ON tc.constraint_name = kcu.constraint_name
    WHERE tc.table_name = $1 AND tc.constraint_type = 'PRIMARY KEY'
) pk ON col.column_name = pk.column_name
LEFT JOIN (
    SELECT column_name
    FROM information_schema.key_column_usage kcu
    JOIN information_schema.table_constraints tc ON tc.constraint_name = kcu.constraint_name
    WHERE tc.table_name = $1 AND tc.constraint_type = 'UNIQUE'
) uq ON col.column_name = uq.column_name
LEFT JOIN (
    SELECT
        kcu.column_name,
        ccu.table_name AS foreign_table,
        ccu.column_name AS foreign_column,
        rc.delete_rule AS on_delete
    FROM information_schema.table_constraints tc
    JOIN information_schema.key_column_usage kcu ON tc.constraint_name = kcu.constraint_name
    JOIN information_schema.constraint_column_usage ccu ON ccu.constraint_name = tc.constraint_name
    JOIN information_schema.referential_constraints rc ON rc.constraint_name = tc.constraint_name
    WHERE tc.table_name = $1 AND tc.constraint_type = 'FOREIGN KEY'
) fk ON col.column_name = fk.column_name
WHERE col.table_name = $1
ORDER BY col.ordinal_position;
      `, [tableName]);

    const containerDiff = { container: tableName, changes: [] };

    if (res.rows.length === 0) {
      containerDiff.desc = `Table '${tableName}' is not present in the database, can create the table`;
      containerDiff.action = dbActions.CREATE_TABLE;
      containerDiff.params = { columns: schema.columns };
      diffs.push(containerDiff);
      continue;
    }

    // Build DB columns map: keep both a readable DDL-like string and normalized spec
    const dbColumns = res.rows.reduce((acc, col) => {
      let coloumn = `${col.column_name} ${col.data_type || ''}`;

      if (col.data_type === 'character varying') {
        coloumn += `(${col.character_maximum_length})`;
      }

      if (col.data_type === 'numeric') {
        coloumn += `(${col.numeric_precision}, ${col.numeric_scale})`;
      }

      if (col.foreign_table && col.foreign_column) {
        coloumn += ` references ${col.foreign_table}(${col.foreign_column})${col.on_delete && col.on_delete !== "NO ACTION" ? ` on delete ${col.on_delete}` : ''}`;
      }

      if (col.is_identity && String(col.is_identity).toLowerCase() === 'yes') {
        if (col.identity_generation && String(col.identity_generation).toLowerCase() === "always") {
          coloumn += " generated always as identity";
        } else {
          coloumn += " generated by default as identity";
        }
      }

      if (col.is_unique) {
        coloumn += " unique";
      }

      if (col.is_nullable && String(col.is_nullable).toLowerCase() === 'no' && !(col.is_identity && String(col.is_identity).toLowerCase() === 'yes')) {
        coloumn += " not null";
      }

      if (col.column_default) {
        if (col.data_type && (col.data_type.startsWith('timestamp') || col.data_type === 'timestamp')) {
          coloumn += ' default CURRENT_TIMESTAMP';
        } else {
          coloumn += ` default ${col.column_default}`;
        }
      }

      const dbSpec = normalizeSpecFromDb(col);

      acc[col.column_name] = {
        type: dbSpec.type,
        spec: dbSpec,
        coloumn
      };
      return acc;
    }, {});

    // Check for missing/mismatched columns
    for (const col of schema.columns) {
      const parsedColumns = buildColumnType(col.type, col);

      // missing column
      if (!dbColumns[col.name]) {
        containerDiff.changes.push({
          desc: `'${col.name}' column is missing; can be added if required.`,
          action: dbActions.ADD_COLUMN,
          params: `ALTER TABLE ${tableName} ADD COLUMN ${parsedColumns};`
        });
        continue;
      }

      // Try normalized compare first (defensive)
      let normalizedOk = false;
      let normalizedError = null;
      try {
        const schemaSpec = normalizeSpecFromSchema(col.name, col);
        const dbSpec = dbColumns[col.name].spec;
        normalizedOk = compareColumnSpec(schemaSpec, dbSpec);
      } catch (e) {
        normalizedError = e;
        normalizedOk = false;
      }

      if (!normalizedOk) {
        // Fallback to original DDL-string equality check to avoid false positives
        const rawMatch = parsedColumns === dbColumns[col.name]?.coloumn;
        if (!rawMatch) {
          // push change — include both normalized objects and raw DDL for debugging
          let expectedSpec = null;
          try { expectedSpec = normalizeSpecFromSchema(col.name, col); } catch (_) { expectedSpec = null; }
          containerDiff.changes.push({
            desc: `'${col.name}' column spec mismatch; can be updated.`,
            action: dbActions.UPDATE_TYPE,
            params: {
              name: col.name,
              expected_ddl: parsedColumns,
              actual_ddl: dbColumns[col.name]?.coloumn,
              normalized_error: normalizedError ? String(normalizedError) : undefined,
              expected_spec: expectedSpec,
              actual_spec: dbColumns[col.name].spec
            }
          });
        }
      }
    }

    const schema_columns = schema.columns.map(c => c.name);

    // Check for extra columns
    for (const col in dbColumns) {
      if (!schema_columns.includes(col)) {
        containerDiff.changes.push({
          desc: `'${col}' column is extra; can be safely removed.`,
          action: dbActions.DELETE_COLUMN,
          params: { name: col }
        });
      }
    }

    if (containerDiff.desc || containerDiff.changes.length > 0) {
      diffs.push(containerDiff);
    } else {
      console.log(`>> ${tableName} passed the db schema check.`)
    }
  }

  if (diffs.length === 0) {
    console.log('>> DB Pre-check: Validating schema successful. Schema Matched!');
    console.log();
    return 0;
  }

  diffs.forEach(d => {
    if (d.desc) console.log(`- ${d.desc}`);
    d.changes.forEach(c => console.log(`  * ${c.desc}`));
  });

  if (isProd) {
    console.error('Schema mismatch in production. Stopping server.');
    console.log("diffs : ", JSON.stringify(diffs, null, 4));
    process.exit(1);
  } else {
    const confirm = await askConfirmation('Apply these changes?');
    if (!confirm) {
      console.log('User declined. Exiting.');
      process.exit(1);
    }

    // Apply top-level action then per-change actions (keeps original behavior)
    for (const diff of diffs) {
      if (diff.action) {
        await runDbAction(diff.action, diff.container, diff.params);
      }
      console.log('Applying changes for container:', diff.container, diff.changes);
      for (const change of diff.changes) {
        await runDbAction(change.action, change.container, change.params);
      }
    }

    return 1;
  }
}
